apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Name }}
data:
  DATABASE_URL: {{ .Values.env.database.url | quote }}
  DATABASE_USERNAME: {{ .Values.env.database.username | quote }}
